<?php

/**
 * FrisbeeGameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrisbeeGameTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object FrisbeeGameTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('FrisbeeGame');
    }
    
    public function getGameByKey($key) {
        $q = $this->createQuery('g')
                ->where('MD5(CONCAT("game:", g.id)) = ?', $key);
        
        if ($q->count() > 0) {
            $game = $q->fetchOne();
            return $game;
        }
        
        return null;
    }

}