<?php

/**
 * FrisbeeGamePlayerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrisbeeGamePlayerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FrisbeeGamePlayerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FrisbeeGamePlayer');
    }
}