<?php

/**
 * FrisbeePlayerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FrisbeePlayerTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object FrisbeePlayerTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('FrisbeePlayer');
    }
    
    public function getUserKey($nickname, $pw) {
        $q = $this->createQuery('p')
                ->where('p.nickname = ? AND p.password = ? AND p.is_active = 1', array($nickname, $pw));
        
        if ($q->count() > 0) {
            $result = $q->fetchOne();
            return $result->getKey();            
        }
        
        return null;
    }
    
    public function getUserByKey($key) {
        $q = $this->createQuery('p')
                ->where('MD5(CONCAT("player:", p.id)) = ?', $key);
        
        if ($q->count() > 0) {
            $user = $q->fetchOne();
            return $user;
        }
        
        return null;
    }

}